### PR TITLE
Add missing bigdescription list item

### PR DESCRIPTION
**Pull request by mbtaylor**

### CODE REVIEW

**Comment by mbtaylor** [comment]
There was a missing item in a bigdescription environment in Appendix A.5.  This screwed up some of the TtH formatting later in the document (**Lots of bold text**).  I've added what I think is reasonable text for the item ("QUDT"), but I'm not certain what the original intention was, so somebody better check (git blame says @nxg wrote this in the first place).

**Comment by nxg** [comment]
This looks entirely plausible – thanks

**Review by nxg — COMMENTED** [review]
That looks good to me

**Review by nxg — APPROVED** [review]
Looks good (still...!)

**Pull request merged**
